/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphical;

import containers.*;
import exceptions.BlenderIsEmptyException;
import exceptions.BlenderOverFlowException;
import fruits.*;
import toppings.*;
import ingredients.*;
import liquids.*;
import historylog.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author عسثق
 */
public class OurApp extends javax.swing.JFrame {

    Blender blender = new Blender();
    private boolean liquidFlag = false, cupFlag = false;

    /**
     * Creates new form OurApp
     */
    public OurApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        liquidsButtonGroup = new javax.swing.ButtonGroup();
        cupSizeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tappedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        everythingFruitfulButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AppleButton = new javax.swing.JToggleButton();
        GrapefruitButton = new javax.swing.JToggleButton();
        BananaButton = new javax.swing.JToggleButton();
        OrangeButton = new javax.swing.JToggleButton();
        BlueberryButton = new javax.swing.JToggleButton();
        MangoButton = new javax.swing.JToggleButton();
        DatesButton = new javax.swing.JToggleButton();
        StrawberryButton = new javax.swing.JToggleButton();
        RoseberryButton = new javax.swing.JToggleButton();
        PineappleButton = new javax.swing.JToggleButton();
        WatermelonButton = new javax.swing.JToggleButton();
        ContinueButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dairyMilkToggleButton = new javax.swing.JToggleButton();
        lemonJuiceToggleButton = new javax.swing.JToggleButton();
        oatMilkToggleButton = new javax.swing.JToggleButton();
        almondMilkToggleButton = new javax.swing.JToggleButton();
        orangeJuiceToggleButton = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sugarjSlider = new javax.swing.JSlider();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        sprinklesToggleButton = new javax.swing.JToggleButton();
        chocolateSauseToggleButton = new javax.swing.JToggleButton();
        whippedCreamToggleButton = new javax.swing.JToggleButton();
        coconutFlakesToggleButton = new javax.swing.JToggleButton();
        caramelToggleButton = new javax.swing.JToggleButton();
        CherryToggleButton = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        smallCupToggleButton = new javax.swing.JToggleButton();
        mediumCupToggleButton = new javax.swing.JToggleButton();
        largeCupToggleButton = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JSeparator();
        finishButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTA = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        CaloriesTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PriceTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ColorPanel = new javax.swing.JPanel();
        FinishButton = new javax.swing.JToggleButton();
        OrderAgianButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tappedPane.setBackground(new java.awt.Color(218, 192, 203));

        jPanel2.setBackground(new java.awt.Color(218, 192, 203));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 80, 148));
        jLabel1.setText("Welcome to ");

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 80, 148));
        jLabel2.setText("Everything Fruitful");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/graphical/icons/welcoming_resized.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(253, 156, 204));

        jPanel6.setBackground(new java.awt.Color(253, 250, 163));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(173, 208, 87));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        everythingFruitfulButton.setBackground(new java.awt.Color(248, 249, 233));
        everythingFruitfulButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        everythingFruitfulButton.setForeground(new java.awt.Color(69, 66, 66));
        everythingFruitfulButton.setText("Everything Fruitful Cocktail");
        everythingFruitfulButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        everythingFruitfulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingFruitfulButtonActionPerformed(evt);
            }
        });

        menuButton.setBackground(new java.awt.Color(248, 249, 233));
        menuButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        menuButton.setForeground(new java.awt.Color(69, 66, 66));
        menuButton.setText("Make your own Drink");
        menuButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(everythingFruitfulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(everythingFruitfulButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tappedPane.addTab("Welcome", jPanel2);

        jPanel3.setBackground(new java.awt.Color(218, 192, 203));

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 80, 148));
        jLabel3.setText("Fruits Menu");

        AppleButton.setBackground(new java.awt.Color(218, 192, 203));
        AppleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AppleButton.setForeground(new java.awt.Color(69, 66, 66));
        AppleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/appleIcon.png"))); // NOI18N
        AppleButton.setText("Apple");
        AppleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AppleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppleButtonActionPerformed(evt);
            }
        });

        GrapefruitButton.setBackground(new java.awt.Color(218, 192, 203));
        GrapefruitButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        GrapefruitButton.setForeground(new java.awt.Color(69, 66, 66));
        GrapefruitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/grapefruit.png"))); // NOI18N
        GrapefruitButton.setText("Grapefruit");
        GrapefruitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GrapefruitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrapefruitButtonActionPerformed(evt);
            }
        });

        BananaButton.setBackground(new java.awt.Color(218, 192, 203));
        BananaButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BananaButton.setForeground(new java.awt.Color(69, 66, 66));
        BananaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/banana.png"))); // NOI18N
        BananaButton.setText("Banana");
        BananaButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        OrangeButton.setBackground(new java.awt.Color(218, 192, 203));
        OrangeButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        OrangeButton.setForeground(new java.awt.Color(69, 66, 66));
        OrangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/orange.png"))); // NOI18N
        OrangeButton.setText("Orange");
        OrangeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BlueberryButton.setBackground(new java.awt.Color(218, 192, 203));
        BlueberryButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        BlueberryButton.setForeground(new java.awt.Color(69, 66, 66));
        BlueberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/blueberry.png"))); // NOI18N
        BlueberryButton.setText("Blueberry");
        BlueberryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        MangoButton.setBackground(new java.awt.Color(218, 192, 203));
        MangoButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        MangoButton.setForeground(new java.awt.Color(69, 66, 66));
        MangoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/mango.png"))); // NOI18N
        MangoButton.setText("Mango");
        MangoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MangoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MangoButtonActionPerformed(evt);
            }
        });

        DatesButton.setBackground(new java.awt.Color(218, 192, 203));
        DatesButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        DatesButton.setForeground(new java.awt.Color(69, 66, 66));
        DatesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/dates.png"))); // NOI18N
        DatesButton.setText("Dates");
        DatesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        StrawberryButton.setBackground(new java.awt.Color(218, 192, 203));
        StrawberryButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        StrawberryButton.setForeground(new java.awt.Color(69, 66, 66));
        StrawberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/strawberryIcon.png"))); // NOI18N
        StrawberryButton.setText("Strawberry");
        StrawberryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RoseberryButton.setBackground(new java.awt.Color(218, 192, 203));
        RoseberryButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        RoseberryButton.setForeground(new java.awt.Color(69, 66, 66));
        RoseberryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/roseberry.png"))); // NOI18N
        RoseberryButton.setText("Roseberry");
        RoseberryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PineappleButton.setBackground(new java.awt.Color(218, 192, 203));
        PineappleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        PineappleButton.setForeground(new java.awt.Color(69, 66, 66));
        PineappleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/pineapple.png"))); // NOI18N
        PineappleButton.setText("Pineapple");
        PineappleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        WatermelonButton.setBackground(new java.awt.Color(218, 192, 203));
        WatermelonButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        WatermelonButton.setForeground(new java.awt.Color(69, 66, 66));
        WatermelonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fruitassets/watermelon.png"))); // NOI18N
        WatermelonButton.setText("Watermelon");
        WatermelonButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ContinueButton.setBackground(new java.awt.Color(236, 80, 148));
        ContinueButton.setFont(new java.awt.Font("Script MT Bold", 0, 29)); // NOI18N
        ContinueButton.setForeground(new java.awt.Color(255, 255, 255));
        ContinueButton.setText("Continue");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BananaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AppleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BlueberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RoseberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(95, 95, 95)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(GrapefruitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(OrangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MangoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StrawberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PineappleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(WatermelonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(124, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AppleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GrapefruitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(OrangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BananaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MangoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BlueberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StrawberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RoseberryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PineappleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(WatermelonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(ContinueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tappedPane.addTab("Fruits menu", jPanel3);

        jPanel4.setBackground(new java.awt.Color(218, 192, 203));

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 80, 148));
        jLabel5.setText("Liquids Menu");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 66, 66));
        jLabel6.setText("Milk:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 66, 66));
        jLabel7.setText("Juice: ");

        dairyMilkToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(dairyMilkToggleButton);
        dairyMilkToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        dairyMilkToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        dairyMilkToggleButton.setText("Dairy Milk");
        dairyMilkToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dairyMilkToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dairyMilkToggleButtonActionPerformed(evt);
            }
        });

        lemonJuiceToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(lemonJuiceToggleButton);
        lemonJuiceToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lemonJuiceToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        lemonJuiceToggleButton.setText("Lemon Juice");
        lemonJuiceToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lemonJuiceToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonJuiceToggleButtonActionPerformed(evt);
            }
        });

        oatMilkToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(oatMilkToggleButton);
        oatMilkToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        oatMilkToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        oatMilkToggleButton.setText("Oat Milk");
        oatMilkToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oatMilkToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oatMilkToggleButtonActionPerformed(evt);
            }
        });

        almondMilkToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(almondMilkToggleButton);
        almondMilkToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        almondMilkToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        almondMilkToggleButton.setText("Almond Milk");
        almondMilkToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        almondMilkToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almondMilkToggleButtonActionPerformed(evt);
            }
        });

        orangeJuiceToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        liquidsButtonGroup.add(orangeJuiceToggleButton);
        orangeJuiceToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        orangeJuiceToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        orangeJuiceToggleButton.setText("Orange Juice");
        orangeJuiceToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orangeJuiceToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeJuiceToggleButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 80, 148));
        jLabel8.setText("Sugar");

        sugarjSlider.setMajorTickSpacing(1);
        sugarjSlider.setMaximum(10);
        sugarjSlider.setMinorTickSpacing(1);
        sugarjSlider.setPaintLabels(true);
        sugarjSlider.setPaintTicks(true);
        sugarjSlider.setToolTipText("");
        sugarjSlider.setValue(0);
        sugarjSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sugarjSlider.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sugarjSliderAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        sugarjSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sugarjSliderMouseDragged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 80, 148));
        jLabel9.setText("Toppings");

        sprinklesToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        sprinklesToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        sprinklesToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        sprinklesToggleButton.setText("Sprinkles");
        sprinklesToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sprinklesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sprinklesToggleButtonActionPerformed(evt);
            }
        });

        chocolateSauseToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        chocolateSauseToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        chocolateSauseToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        chocolateSauseToggleButton.setText("Chocolate Sause");
        chocolateSauseToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chocolateSauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateSauseToggleButtonActionPerformed(evt);
            }
        });

        whippedCreamToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        whippedCreamToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        whippedCreamToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        whippedCreamToggleButton.setText("Whipped Cream");
        whippedCreamToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        whippedCreamToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whippedCreamToggleButtonActionPerformed(evt);
            }
        });

        coconutFlakesToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        coconutFlakesToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        coconutFlakesToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        coconutFlakesToggleButton.setText("Coconut Flakes");
        coconutFlakesToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coconutFlakesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coconutFlakesToggleButtonActionPerformed(evt);
            }
        });

        caramelToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        caramelToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        caramelToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        caramelToggleButton.setText("Caramel");
        caramelToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        caramelToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caramelToggleButtonActionPerformed(evt);
            }
        });

        CherryToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        CherryToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        CherryToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        CherryToggleButton.setText("Cherry");
        CherryToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CherryToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CherryToggleButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 80, 148));
        jLabel10.setText("Cup Size:");

        smallCupToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        cupSizeButtonGroup.add(smallCupToggleButton);
        smallCupToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        smallCupToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        smallCupToggleButton.setText("Small Cup");
        smallCupToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        smallCupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallCupToggleButtonActionPerformed(evt);
            }
        });

        mediumCupToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        cupSizeButtonGroup.add(mediumCupToggleButton);
        mediumCupToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        mediumCupToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        mediumCupToggleButton.setText("Medium Cup");
        mediumCupToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mediumCupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumCupToggleButtonActionPerformed(evt);
            }
        });

        largeCupToggleButton.setBackground(new java.awt.Color(218, 192, 203));
        cupSizeButtonGroup.add(largeCupToggleButton);
        largeCupToggleButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        largeCupToggleButton.setForeground(new java.awt.Color(59, 54, 54));
        largeCupToggleButton.setText("Large Cup");
        largeCupToggleButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        largeCupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeCupToggleButtonActionPerformed(evt);
            }
        });

        finishButton.setBackground(new java.awt.Color(236, 80, 148));
        finishButton.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        finishButton.setForeground(new java.awt.Color(218, 192, 203));
        finishButton.setText("Finish");
        finishButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 80, 148), 5, true));
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(206, 206, 206)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(212, 212, 212)
                            .addComponent(jLabel10))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(sugarjSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dairyMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(oatMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(almondMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(134, 134, 134)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lemonJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(orangeJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(jLabel9))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(coconutFlakesToggleButton)
                                        .addComponent(sprinklesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(9, 9, 9))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(smallCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chocolateSauseToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(caramelToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CherryToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(whippedCreamToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(mediumCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(largeCupToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addContainerGap(77, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(dairyMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(oatMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(almondMilkToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(lemonJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(orangeJuiceToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(sugarjSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sprinklesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chocolateSauseToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(whippedCreamToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(coconutFlakesToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(caramelToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CherryToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(smallCupToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(largeCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mediumCupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(28, 28, 28)
                    .addComponent(finishButton)
                    .addContainerGap()))
        );

        tappedPane.addTab("Liquids-sugar-toppings", jPanel4);

        jPanel8.setBackground(new java.awt.Color(218, 192, 203));

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 80, 148));
        jLabel11.setText("Your Order:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(79, 75, 73));
        jLabel12.setText("You Ordered:");

        OrderTA.setColumns(20);
        OrderTA.setRows(5);
        jScrollPane1.setViewportView(OrderTA);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(79, 75, 73));
        jLabel13.setText("Total Calories:");

        CaloriesTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(79, 75, 73));
        jLabel14.setText("Total Price:");

        PriceTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(79, 75, 73));
        jLabel15.setText("Color: ");

        javax.swing.GroupLayout ColorPanelLayout = new javax.swing.GroupLayout(ColorPanel);
        ColorPanel.setLayout(ColorPanelLayout);
        ColorPanelLayout.setHorizontalGroup(
            ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        ColorPanelLayout.setVerticalGroup(
            ColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        FinishButton.setBackground(new java.awt.Color(218, 192, 203));
        FinishButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        FinishButton.setForeground(new java.awt.Color(69, 66, 66));
        FinishButton.setText("Check out");
        FinishButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishButtonActionPerformed(evt);
            }
        });

        OrderAgianButton.setBackground(new java.awt.Color(218, 192, 203));
        OrderAgianButton.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        OrderAgianButton.setForeground(new java.awt.Color(69, 66, 66));
        OrderAgianButton.setText("Order another cocktail");
        OrderAgianButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OrderAgianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderAgianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CaloriesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(45, 45, 45)
                                .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(115, 115, 115)
                                        .addComponent(ColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(OrderAgianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)))
                    .addContainerGap(186, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(22, 22, 22)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CaloriesTF))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PriceTF))
                    .addGap(16, 16, 16)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addComponent(FinishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(OrderAgianButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(132, 132, 132)))
        );

        tappedPane.addTab("Result for own drink", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tappedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tappedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void everythingFruitfulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_everythingFruitfulButtonActionPerformed
        EverythingFruitfulDrinks menu = new EverythingFruitfulDrinks();
        menu.show();
        dispose();
        //everythingFruitful.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_everythingFruitfulButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        tappedPane.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuButtonActionPerformed

    private void MangoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MangoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MangoButtonActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed

        if (AppleButton.isSelected()) {
            try {
                blender.addIngredient(new Apple(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            }
        }
        if (BananaButton.isSelected()) {
            try {
                blender.addIngredient(new Banana(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (GrapefruitButton.isSelected()) {
            try {
                blender.addIngredient(new Grapefruits(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (BlueberryButton.isSelected()) {
            try {
                blender.addIngredient(new Blueberry(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (DatesButton.isSelected()) {
            try {
                blender.addIngredient(new Dates(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (MangoButton.isSelected()) {
            try {
                blender.addIngredient(new Mango(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (OrangeButton.isSelected()) {
            try {
                blender.addIngredient(new Orange(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (PineappleButton.isSelected()) {
            try {
                blender.addIngredient(new Pineapple(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (RoseberryButton.isSelected()) {
            try {
                blender.addIngredient(new Raspberry(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (StrawberryButton.isSelected()) {
            try {
                blender.addIngredient(new Strawberry(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        if (WatermelonButton.isSelected()) {
            try {
                blender.addIngredient(new Watermelon(2));
                // blender.addIgredient(new Apple(2));
            } catch (BlenderOverFlowException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        System.out.println(blender.getIngredientsString());
        tappedPane.setSelectedIndex(2);

        // TODO add your handling code here:
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void GrapefruitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrapefruitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrapefruitButtonActionPerformed

    private void AppleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppleButtonActionPerformed

    private void dairyMilkToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dairyMilkToggleButtonActionPerformed
        liquidFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_dairyMilkToggleButtonActionPerformed

    private void lemonJuiceToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonJuiceToggleButtonActionPerformed

        liquidFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_lemonJuiceToggleButtonActionPerformed

    private void oatMilkToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oatMilkToggleButtonActionPerformed
        liquidFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_oatMilkToggleButtonActionPerformed

    private void almondMilkToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almondMilkToggleButtonActionPerformed
        liquidFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_almondMilkToggleButtonActionPerformed

    private void orangeJuiceToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeJuiceToggleButtonActionPerformed
        liquidFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeJuiceToggleButtonActionPerformed

    private void sugarjSliderAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sugarjSliderAncestorAdded
        cupFlag = true;
        finishButton.setEnabled(cupFlag);
        // TODO add your handling code here:
    }//GEN-LAST:event_sugarjSliderAncestorAdded

    private void sugarjSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sugarjSliderMouseDragged
        cupFlag = true;
        finishButton.setEnabled(cupFlag);
        // TODO add your handling code here:
    }//GEN-LAST:event_sugarjSliderMouseDragged

    private void sprinklesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sprinklesToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sprinklesToggleButtonActionPerformed

    private void chocolateSauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateSauseToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chocolateSauseToggleButtonActionPerformed

    private void whippedCreamToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whippedCreamToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_whippedCreamToggleButtonActionPerformed

    private void coconutFlakesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coconutFlakesToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coconutFlakesToggleButtonActionPerformed

    private void caramelToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caramelToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caramelToggleButtonActionPerformed

    private void CherryToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CherryToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CherryToggleButtonActionPerformed

    private void smallCupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallCupToggleButtonActionPerformed
        cupFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_smallCupToggleButtonActionPerformed

    private void mediumCupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumCupToggleButtonActionPerformed
        cupFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_mediumCupToggleButtonActionPerformed

    private void largeCupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeCupToggleButtonActionPerformed
        cupFlag = true;
        // TODO add your handling code here:
    }//GEN-LAST:event_largeCupToggleButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        int sugar;
        blender = new Blender();
        if (!liquidFlag) {
            JOptionPane.showMessageDialog(this, "You must choose atleast one of the liquids", "Warning", JOptionPane.ERROR_MESSAGE);
        }

        if (!cupFlag) {
            JOptionPane.showMessageDialog(this, "You must choose a Cup Size", "Warning", JOptionPane.ERROR_MESSAGE);
        }

        try {
            if (dairyMilkToggleButton.isSelected()) {
                blender.addIngredient(new DairyMilk());
            } else if (oatMilkToggleButton.isSelected()) {
                blender.addIngredient(new OatMilk());
            } else if (orangeJuiceToggleButton.isSelected()) {
                blender.addIngredient(new OrangeJuice());
            } else if (lemonJuiceToggleButton.isSelected()) {
                blender.addIngredient(new LemonJuice());
            } else if (almondMilkToggleButton.isSelected()) {
                blender.addIngredient(new AlmondMilk());
            }

            sugar = sugarjSlider.getValue();
            //System.out.println(sugar);
            System.out.println(blender.getIngredientsString());
            blender.addIngredient(new Sugar(sugar));

            if (sprinklesToggleButton.isSelected()) {
                blender.addIngredient(new Sprinkles());
            }

            if (caramelToggleButton.isSelected()) {
                blender.addIngredient(new Caramel());
            }

            if (chocolateSauseToggleButton.isSelected()) {
                blender.addIngredient(new ChocolateSause());
            }

            if (whippedCreamToggleButton.isSelected()) {
                blender.addIngredient(new WhippedCream());
            }

            if (coconutFlakesToggleButton.isSelected()) {
                blender.addIngredient(new CoconutFlakes());
            }

            if (CherryToggleButton.isSelected()) {
                blender.addIngredient(new Cherry());
            }
            
            try {
                blender.blend();
            } catch (BlenderIsEmptyException ex) {
                java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            // cups
            Cup cup = null;
            if (smallCupToggleButton.isSelected()) {
                double numberOfCups = blender.getCocktailVolume() / SmallCup.getCupCapacity();
                cup = new SmallCup(numberOfCups);
                try {
                    blender.pour(cup);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    //Logger.getLogger(LiquidsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (mediumCupToggleButton.isSelected()) {
                double numberOfCups = blender.getCocktailVolume() / MediumCup.getCupCapacity();
                cup = new MediumCup(numberOfCups);

                try {
                    blender.pour(cup);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    //Logger.getLogger(LiquidsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (largeCupToggleButton.isSelected()) {
                double numberOfCups = blender.getCocktailVolume() / LargeCup.getCupCapacity();
                cup = new LargeCup(numberOfCups);
                try {
                    blender.pour(cup);
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    //Logger.getLogger(LiquidsGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "You must choose a Cup Size", "Warning", JOptionPane.ERROR_MESSAGE);
            }
            if (cup != null) {
                
               

                OrderTA.setText(blender.getIngredientsString());
                CaloriesTF.setText("" + cup.getCocktailCalories());
                PriceTF.setText("" + cup.getPrice());
                int r=(int) (blender.getCocktailColor().getRed());
                int g=(int) (blender.getCocktailColor().getGreen());
                int b=(int) (blender.getCocktailColor().getBlue());
                //Color color = new Color((int) ((int) (blender.getCocktailColor().getRed()),(blender.getCocktailColor().getGreen()), (blender.getCocktailColor().getBlue()));
                ColorPanel.setBackground(new Color(r,g,b));

                tappedPane.setSelectedIndex(3);

            }
        } catch (BlenderOverFlowException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        //        catch(Exception e)
        //        {
        //            JOptionPane.showMessageDialog(this, "another exception");
        //
        //        }

    }//GEN-LAST:event_finishButtonActionPerformed

    private void FinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_FinishButtonActionPerformed

    private void OrderAgianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderAgianButtonActionPerformed
        // TODO add your handling code here:
        Welcome welcome = new Welcome();
        welcome.show();
        dispose();
    }//GEN-LAST:event_OrderAgianButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OurApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OurApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AppleButton;
    private javax.swing.JToggleButton BananaButton;
    private javax.swing.JToggleButton BlueberryButton;
    private javax.swing.JTextField CaloriesTF;
    private javax.swing.JToggleButton CherryToggleButton;
    private javax.swing.JPanel ColorPanel;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JToggleButton DatesButton;
    private javax.swing.JToggleButton FinishButton;
    private javax.swing.JToggleButton GrapefruitButton;
    private javax.swing.JToggleButton MangoButton;
    private javax.swing.JToggleButton OrangeButton;
    private javax.swing.JToggleButton OrderAgianButton;
    private javax.swing.JTextArea OrderTA;
    private javax.swing.JToggleButton PineappleButton;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JToggleButton RoseberryButton;
    private javax.swing.JToggleButton StrawberryButton;
    private javax.swing.JToggleButton WatermelonButton;
    private javax.swing.JToggleButton almondMilkToggleButton;
    private javax.swing.JToggleButton caramelToggleButton;
    private javax.swing.JToggleButton chocolateSauseToggleButton;
    private javax.swing.JToggleButton coconutFlakesToggleButton;
    private javax.swing.ButtonGroup cupSizeButtonGroup;
    private javax.swing.JToggleButton dairyMilkToggleButton;
    private javax.swing.JButton everythingFruitfulButton;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToggleButton largeCupToggleButton;
    private javax.swing.JToggleButton lemonJuiceToggleButton;
    private javax.swing.ButtonGroup liquidsButtonGroup;
    private javax.swing.JToggleButton mediumCupToggleButton;
    private javax.swing.JButton menuButton;
    private javax.swing.JToggleButton oatMilkToggleButton;
    private javax.swing.JToggleButton orangeJuiceToggleButton;
    private javax.swing.JToggleButton smallCupToggleButton;
    private javax.swing.JToggleButton sprinklesToggleButton;
    private javax.swing.JSlider sugarjSlider;
    private javax.swing.JTabbedPane tappedPane;
    private javax.swing.JToggleButton whippedCreamToggleButton;
    // End of variables declaration//GEN-END:variables
}
